#pragma once
#include "EZ-Template/drive/drive.hpp"
#include "api.h"
void intake_in();
void intake_out_slow();
void intake_out_fast();
void intake_stop();
void flywheel_low();
void flywheel_high();
void flywheel_ultra_high();
void flywheel_stop();
void drive_lock();
int double_shoot_function();
int single_shoot_function();
int triple_shoot_function();
int turn_pid_180_function();
void triple_shoot();
void turn_pid_180();
void single_shoot();
void double_shoot();