#include "api.h"
void intake_in();
void intake_out();
void intake_stop();
void flywheel_low();
void flywheel_high();
void flywheel_stop();
void drive_lock();
int triple_shoot_function();
int turn_pid_180_function();
void triple_shoot();
void turn_pid_180();