#pragma once
#include "EZ-Template/drive/drive.hpp"
void wait_until_change_speed();
void swing_example();
void combining_movements();
void interfered_example();
void default_constants();
void side_2_tiles();
void side_1_tile();